---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-monolithic
  labels:
    app: k8s-monolithic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-monolithic
  template:
    metadata:
      labels:
        app: k8s-monolithic
    spec:
      containers:
        - name: monolithic
          image: master-node:5000/monolithic
---
apiVersion: v1
kind: Service
metadata:
  name: monolithic-passthrough
  namespace: default
spec:
  ports:
  - name: monolithic-port
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: k8s-monolithic